"use client";

import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import { AlertTriangle, Check, ChevronLeft, ChevronRight, Circle, Expand, LoaderCircle, Monitor, ShieldCheck, Video, Wifi, X } from "lucide-react";
import { Question, QuestionRenderer } from "./QuestionRenderer";
import { useAntiCheat, IntegrityEvent } from "../hooks/useAntiCheat";
import { useExamTimer } from "../hooks/useExamTimer";

const questions: Question[] = [
  { id: "q1", type: "single", prompt: "Which metric best describes the percentage of users who complete a desired action in a product funnel?", options: [{ id: "a", label: "Conversion rate" }, { id: "b", label: "Retention cohort" }, { id: "c", label: "Net promoter score" }, { id: "d", label: "Page latency" }] },
  { id: "q2", type: "multiple", prompt: "Which practices help produce a reliable experiment? Select all that apply.", options: [{ id: "a", label: "Define a measurable hypothesis" }, { id: "b", label: "Change several variables at once" }, { id: "c", label: "Use a representative sample" }, { id: "d", label: "Set success criteria before launch" }] },
  { id: "q3", type: "boolean", prompt: "A statistically significant result always means the outcome is meaningful to the business.", options: [{ id: "true", label: "True" }, { id: "false", label: "False" }] },
];
const policy = { requireFullscreen: true, requireCamera: true, requireMicrophone: false, maxViolations: 3, autoSubmitOnViolation: false };
type Stage = "check" | "permission" | "exam" | "submitted" | "terminated";

export function AssessmentTaker({ assessmentId }: { assessmentId: string }) {
  const attemptId = useRef(`attempt-${assessmentId}-${Date.now()}`).current;
  const endingAttempt = useRef(false);
  const [stage, setStage] = useState<Stage>("check"); const [camera, setCamera] = useState<"idle" | "ready" | "denied">("idle"); const [online, setOnline] = useState(true); const [current, setCurrent] = useState(0); const [answers, setAnswers] = useState<Record<string, string | string[]>>({}); const [saved, setSaved] = useState<"saved" | "saving" | "offline">("saved"); const [events, setEvents] = useState<IntegrityEvent[]>([]); const [warning, setWarning] = useState<string | null>(null); const [fullscreenExit, setFullscreenExit] = useState(false); const [dialog, setDialog] = useState<"submit" | "exit" | null>(null); const [expiresAt] = useState(() => Date.now() + 45 * 60 * 1000);
  useEffect(() => { const update = () => setOnline(navigator.onLine); update(); window.addEventListener("online", update); window.addEventListener("offline", update); return () => { window.removeEventListener("online", update); window.removeEventListener("offline", update); }; }, []);
  useEffect(() => { const raw = localStorage.getItem(`assessment:${assessmentId}:answers`); if (raw) setAnswers(JSON.parse(raw)); }, [assessmentId]);
  const complete = useCallback((reason: "submitted" | "terminated" = "submitted") => { endingAttempt.current = true; localStorage.setItem(`assessment:${assessmentId}:attempt`, JSON.stringify({ attemptId, assessmentId, answers, status: reason, submittedAt: new Date().toISOString() })); localStorage.removeItem(`assessment:${assessmentId}:answers`); if (document.fullscreenElement) document.exitFullscreen().catch(() => undefined); window.location.assign(`/user/results/${attemptId}?status=${reason}`); }, [answers, assessmentId, attemptId]);
  const timer = useExamTimer(expiresAt, stage === "exam", () => complete("submitted"));
  const logEvent = useCallback((event: IntegrityEvent) => { if (endingAttempt.current) return; setEvents(previous => [...previous, event]); if (event.type === "FULLSCREEN_EXIT") { setFullscreenExit(true); return; } setWarning("An examination integrity event was recorded."); if (policy.autoSubmitOnViolation && events.length + 1 >= policy.maxViolations) complete("terminated"); }, [complete, events.length]);
  useAntiCheat({ active: stage === "exam", assessmentId, attemptId, requireFullscreen: policy.requireFullscreen, onEvent: logEvent });
  const saveAnswer = (answer: string | string[] | undefined) => { if (!answer) return; const next = { ...answers, [questions[current].id]: answer }; setAnswers(next); localStorage.setItem(`assessment:${assessmentId}:answers`, JSON.stringify(next)); setSaved(online ? "saving" : "offline"); window.setTimeout(() => setSaved(online ? "saved" : "offline"), 450); };
  const requestCamera = async () => { try { const stream = await navigator.mediaDevices.getUserMedia({ video: true }); stream.getTracks().forEach(track => track.stop()); setCamera("ready"); } catch { setCamera("denied"); } };
  const begin = async () => { if (policy.requireFullscreen) { try { await document.documentElement.requestFullscreen(); } catch { setWarning("Fullscreen could not be started. Please allow fullscreen to continue."); return; } } setStage("exam"); };
  const answered = Object.keys(answers).length; const question = questions[current]; const monitoring = policy.requireCamera && camera === "ready";
  if (stage === "check") return <CheckScreen online={online} onContinue={() => setStage(policy.requireCamera ? "permission" : "exam")} />;
  if (stage === "permission") return <PermissionScreen camera={camera} onEnable={requestCamera} onContinue={begin} />;
  if (stage === "submitted" || stage === "terminated") return <CompletionScreen terminated={stage === "terminated"} />;
  return <main className="exam-shell"><header className="exam-header"><strong>Product Analytics Fundamentals</strong><div className={`exam-timer ${timer.low ? "low" : ""}`}>{timer.label}</div><button onClick={() => setDialog("exit")} className="exam-exit"><X size={16}/> Exit</button></header>{!online && <div className="exam-banner"><AlertTriangle size={16}/> Connection interrupted. Answers are stored locally and will sync when restored.</div>}<div className="exam-body"><div className="exam-progress"><span>Question {current + 1} of {questions.length}</span><i><em style={{ width: `${((current + 1) / questions.length) * 100}%` }}/></i></div><QuestionRenderer question={question} answer={answers[question.id]} onAnswer={saveAnswer}/></div><footer className="exam-footer"><span className={`monitoring ${monitoring ? "active" : ""}`}><Circle size={8} fill="currentColor"/> {monitoring ? "Monitoring active" : "Browser monitoring active"}</span><span className="save-status">{saved === "saving" ? <><LoaderCircle size={13} className="spin"/> Saving…</> : saved === "offline" ? "Stored locally" : <><Check size={14}/> Saved</>}</span><div className="exam-actions"><button className="previous" disabled={current === 0} onClick={() => setCurrent(value => value - 1)}><ChevronLeft size={16}/> Previous</button>{current === questions.length - 1 ? <button className="submit-exam" onClick={() => setDialog("submit")}>Submit assessment</button> : <button className="next" onClick={() => setCurrent(value => value + 1)}>Next <ChevronRight size={16}/></button>}</div></footer>{fullscreenExit && <FullscreenAutoSubmit assessmentId={assessmentId} attemptId={attemptId} answers={answers} onReturn={async () => { try { await document.documentElement.requestFullscreen(); setFullscreenExit(false); } catch { setWarning("Fullscreen could not be restored. Please allow fullscreen to continue."); } }} />}{warning && <Warning text={warning} onReturn={async () => { try { await document.documentElement.requestFullscreen(); setWarning(null); } catch { /* browser permission required */ } }} onClose={() => setWarning(null)} />}{dialog && <Dialog type={dialog} answered={answered} total={questions.length} onCancel={() => setDialog(null)} onConfirm={() => dialog === "submit" ? complete() : window.location.assign("/user")} />}</main>;
}
function CheckScreen({ online, onContinue }: { online: boolean; onContinue: () => void }) { return <main className="preexam"><section className="preexam-card"><p className="exam-kicker">System check</p><h1>Before you begin</h1><p>Confirm your device is ready. Only required checks are shown.</p><div className="check-list"><CheckRow icon={Video} label="Camera" value="Required for this assessment" state="ready"/><CheckRow icon={Wifi} label="Network" value={online ? "Connected" : "Connection unavailable"} state={online ? "ready" : "error"}/><CheckRow icon={Expand} label="Fullscreen" value="Supported" state="ready"/><CheckRow icon={Monitor} label="Browser" value="Supported" state="ready"/></div><button disabled={!online} className="exam-primary" onClick={onContinue}>Continue <ChevronRight size={17}/></button></section></main>; }
function PermissionScreen({ camera, onEnable, onContinue }: { camera: "idle" | "ready" | "denied"; onEnable: () => void; onContinue: () => void }) { return <main className="preexam"><section className="preexam-card"><div className="permission-icon"><Video size={25}/></div><p className="exam-kicker">Permission required</p><h1>Enable your camera</h1><p>Your camera is required for this assessment. A small monitoring indicator will remain visible while you work.</p>{camera === "denied" && <p className="permission-error">Camera access was denied. Enable it in your browser, then try again.</p>}{camera === "ready" ? <div className="camera-ready"><Check size={18}/> Camera ready</div> : <button className="exam-primary" onClick={onEnable}>Enable camera</button>}{camera === "ready" && <button className="exam-primary" onClick={onContinue}>Enter fullscreen <Expand size={17}/></button>}</section></main>; }
function CheckRow({ icon: Icon, label, value, state }: { icon: typeof Video; label: string; value: string; state: "ready" | "error" }) { return <div className="check-row"><Icon size={18}/><div><strong>{label}</strong><span>{value}</span></div><b className={state}>{state === "ready" ? <Check size={16}/> : <AlertTriangle size={16}/>}</b></div>; }
function Warning({ text, onReturn, onClose }: { text: string; onReturn: () => void; onClose: () => void }) { return <div className="exam-overlay"><section className="exam-dialog warning-dialog"><AlertTriangle size={27}/><p className="exam-kicker">Examination warning</p><h2>{text}</h2><p>This event has been recorded. Detection signals are reviewed according to the assessment policy.</p><div><button className="exam-primary" onClick={onReturn}>Return to fullscreen</button><button className="dialog-link" onClick={onClose}>Continue</button></div></section></div>; }
function FullscreenAutoSubmit({ assessmentId, attemptId, answers, onReturn }: { assessmentId: string; attemptId: string; answers: Record<string, string | string[]>; onReturn: () => void }) { const [remaining, setRemaining] = useState(3); useEffect(() => { const ticker = window.setInterval(() => setRemaining(value => Math.max(0, value - 1)), 1000); const submit = window.setTimeout(() => { localStorage.setItem(`assessment:${assessmentId}:attempt`, JSON.stringify({ attemptId, assessmentId, answers, status: "auto_submitted", submittedAt: new Date().toISOString() })); localStorage.removeItem(`assessment:${assessmentId}:answers`); window.location.assign(`/user/results/${attemptId}?status=auto_submitted`); }, 3000); return () => { window.clearInterval(ticker); window.clearTimeout(submit); }; }, [answers, assessmentId, attemptId]); return <div className="exam-overlay"><section className="exam-dialog warning-dialog auto-submit-dialog"><AlertTriangle size={27}/><p className="exam-kicker">Examination interrupted</p><h2>Fullscreen mode was exited.</h2><p>Return to the assessment within {remaining} second{remaining === 1 ? "" : "s"}; otherwise your work will be automatically submitted.</p><div className="countdown-ring">{remaining}</div><button className="exam-primary" onClick={onReturn}>Return to assessment</button></section></div>; }
function Dialog({ type, answered, total, onCancel, onConfirm }: { type: "submit" | "exit"; answered: number; total: number; onCancel: () => void; onConfirm: () => void }) { const submit = type === "submit"; return <div className="exam-overlay"><section className="exam-dialog"><p className="exam-kicker">{submit ? "Submit assessment" : "Exit assessment"}</p><h2>{submit ? "Are you ready to submit?" : "Leave this assessment?"}</h2><p>{submit ? answered === total ? "You have answered all questions. Once submitted, you cannot return." : `You have answered ${answered} of ${total} questions. ${total - answered} remain unanswered.` : "Leaving may terminate your attempt, depending on this assessment’s policy."}</p><div><button className="dialog-link" onClick={onCancel}>{submit ? "Cancel" : "Continue exam"}</button><button className={submit ? "submit-exam" : "danger-button"} onClick={onConfirm}>{submit ? "Submit assessment" : "Exit"}</button></div></section></div>; }
function CompletionScreen({ terminated }: { terminated: boolean }) { return <main className="preexam"><section className="preexam-card completion"><div className="permission-icon"><ShieldCheck size={26}/></div><p className="exam-kicker">{terminated ? "Assessment terminated" : "Assessment submitted"}</p><h1>{terminated ? "Integrity threshold reached" : "Your answers were recorded"}</h1><p>{terminated ? "Your assessment was automatically submitted because the configured examination integrity threshold was reached." : "Your assessment has been successfully submitted. Results will be available according to your assessment settings."}</p><Link href="/user" className="exam-primary">Close</Link></section></main>; }
